const $body = document.querySelector("body") /*To use it later for the background*/
const $backgroundImage = $body.querySelector(".backgroundImage")
const $player = $body.querySelector(".player")
const $introductiveText = $player.querySelector(".introductiveText")
const $title = $introductiveText.querySelector(".title")
const $subtitle = $introductiveText.querySelector(".subtitle")
const $artist = $subtitle.querySelector(".artistName")
const names = ['"Mozart"', '"Bach"', '"Beethoven"']
const $mainInterface = $player.querySelector(".mainInterface")
const $sounds = $player.querySelectorAll(".sounds audio")
const $track1 = $player.querySelector(".mozart")
const $track2 = $player.querySelector(".beethoven")
const $track3 = $player.querySelector(".bach")
const $artistList = $player.querySelector(".artistList")
const $covers = $artistList.querySelectorAll("div")
const $seekBar = $player.querySelector(".seekBar")
const $fillBar = $seekBar.querySelector(".fillBar")
const $volumeContainer = $player.querySelector(".volume")
const $volume = $volumeContainer.querySelector(".volumeButton")
const $totalDuration = $player.querySelector(".controls .totalDuration")
const $currentDuration = $player.querySelector(".controls .currentDuration")
const $warningText = document.querySelector(".warningText")
const $lectureControl = $player.querySelector(".mainButtons")
const $playButton = $lectureControl.querySelector(".playButton")
const $pausedButton = $lectureControl.querySelector(".pausedButton")
const $previousButton = $lectureControl.querySelector(".previousButton")
const $nextButton = $lectureControl.querySelector(".nextButton")
const $description = $player.querySelector(".controls .description")
const $artisticName = $description.querySelector(".artist")
const $musicTitle = $description.querySelector(".musicTitle")
const $help = $player.querySelector(".help")
const $indications = $help.querySelector(".indications")
const $loader = $body.querySelector(".loader")
const $musicLoader = $body.querySelector(".musicLoader")
let currentSound = 0



const player = new Player()
player.parse()

const introductiveInterface = new IntroductiveInterface()
introductiveInterface.parse()

const speechRecognition = new SpeechRecognition()
speechRecognition.parse()